export const posts = [
  {
    id: 1,
    title: "Desarrollo motor en los primeros 12 meses",
    slug: "desarrollo-motor-12-meses",
    excerpt: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    content: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p><p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><h2>Hitos del desarrollo</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi.</p>",
    categoria: "Desarrollo Infantil",
    categoriaSlug: "desarrollo-infantil",
    fecha: "2026-05-15",
    imagen: "/assets/img/placeholder-1.jpg",
    autor: "Dra. María González",
  },
  {
    id: 2,
    title: "Alimentación complementaria: guía para padres",
    slug: "alimentacion-complementaria-guia",
    excerpt: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    content: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p><p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>",
    categoria: "Nutrición",
    categoriaSlug: "nutricion",
    fecha: "2026-05-10",
    imagen: "/assets/img/placeholder-2.jpg",
    autor: "Nut. Carolina Silva",
  },
  {
    id: 3,
    title: "La importancia del sueño infantil",
    slug: "importancia-sueno-infantil",
    excerpt: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    content: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>",
    categoria: "Salud",
    categoriaSlug: "salud",
    fecha: "2026-05-05",
    imagen: "/assets/img/placeholder-3.jpg",
    autor: "Dr. Pablo Martínez",
  },
  {
    id: 4,
    title: "Estimulación temprana: actividades por edad",
    slug: "estimulacion-temprana-actividades",
    excerpt: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    content: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>",
    categoria: "Estimulación Temprana",
    categoriaSlug: "estimulacion-temprana",
    fecha: "2026-04-28",
    imagen: "/assets/img/placeholder-4.jpg",
    autor: "Ter. Ocup. Andrea Vega",
  },
  {
    id: 5,
    title: "Vacunación infantil: mitos y verdades",
    slug: "vacunacion-infantil-mitos",
    excerpt: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    content: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>",
    categoria: "Salud",
    categoriaSlug: "salud",
    fecha: "2026-04-20",
    imagen: "/assets/img/placeholder-5.jpg",
    autor: "Dr. Pablo Martínez",
  },
  {
    id: 6,
    title: "Juego y aprendizaje en la primera infancia",
    slug: "juego-aprendizaje-primera-infancia",
    excerpt: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    content: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>",
    categoria: "Desarrollo Infantil",
    categoriaSlug: "desarrollo-infantil",
    fecha: "2026-04-15",
    imagen: "/assets/img/placeholder-6.jpg",
    autor: "Dra. María González",
  },
  {
    id: 7,
    title: "Prevención de accidentes en el hogar",
    slug: "prevencion-accidentes-hogar",
    excerpt: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    content: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>",
    categoria: "Salud",
    categoriaSlug: "salud",
    fecha: "2026-04-08",
    imagen: "/assets/img/placeholder-7.jpg",
    autor: "Dra. María González",
  },
];

export function getLatestPosts(limit = 3) {
  return [...posts]
    .sort((a, b) => new Date(b.fecha).getTime() - new Date(a.fecha).getTime())
    .slice(0, limit);
}
